title: "Ajay Singh"
email: admin@ajaysingh.com.np
description: >- # this means to ignore newlines until "baseurl:"
  A basic blog site with jekyll and github pages. More description comming soon.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ajaysingh.com.np" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: singh_ajaykumar
github_username:  mentormaya

# Build settings
theme: minima
plugins:
  - jekyll-feed
